### ISSUE TITLE
domain is for sale

### ISSUE THREAD

**Issue by greenbigfrog** [SergioFierens/ai4r#37]
Please link/host/whatever the original site somewhere again. The domain listed everywhere didn't get renewed as it seams

**Comment by tobypinder** [comment]
+1, it's pretty malwarey now with it's redirects, backed away quick. Should at least be removed from documentation altogether if not rehosted.

**Comment by SergioFierens** [comment]
I just removed the old domain from the repo, and added the GitHub repo URL instead. Thank you for pointing this out.

**Comment by SergioFierens** [comment]
resolved
