### ISSUE TITLE
Porting parts of the code

### ISSUE THREAD

**Issue by bararchy** [SergioFierens/ai4r#38]
@SergioFierens 

I took part of your code that was ported to Crystal-lang for an ANN project I'm doing (MIT licensed), just wanted to make sure it's ok with you [code here](https://github.com/bararchy/crystal-ann/blob/master/src/crystal-ann/neuralnet.cr) I gave you and the repo credits for the work.

Hope it's ok.

**Comment by SergioFierens** [comment]
Perfectly fine. I'm glad it was helpful.
